export var demoAccounts = "(1118, 1206, 1411)";
export var expectationList = {
  takilmak: new Set(),
  kisaSureli: new Set(),
  uzunSureli: new Set(),
  yeniArkadas: new Set(),
  etkinlikBuddy: new Set(),
  bilmiyorum: new Set(),
};
export var genderPreference = {
  women: new Set(),
  men: new Set(),
  non_binary: new Set(),
  hetero: new Set(),
  homo: new Set(),
  bisexual: new Set(),
  pansexual: new Set(),
  asexual: new Set(),
};
export var dailyStats = {
  newUser: 0,
  frozenUser: 0,
  deletedUser: 0,
  dailyRetention: 0,
  dailyUnmatch: 0,
  dailyMatch: 0,
  dailyMatchonEvent: 0,
  totalSwipe: 0,
  dailySwipe: 0,
  dailyLike: 0,
  dailyDislike: 0,
  dailyEventLike: 0,
  newEvents: 0,
  dailyNewReport: 0,
  dailyNewMessages: 0,
  totalMessages: 0,
};
export var cacheStats = {
  cacheSize: 0,
  frozenUser: 0,
  dailyUnmatch: 0,
  newEvents: 0,
  dailyEventLike: 0,
  dailyEventClick: 0,
  dailyDetailClick: 0,
  dailyLinkClick: 0,
  dailyNewReport: 0,
};
export var appLists = {
  genderList: [
    { key: 0, choice: "Kadın" },
    { key: 1, choice: "Erkek" },
    { key: 2, choice: "Non-Binary" },
    { key: 3, choice: "Belirtmek İstemiyorum" },
  ],
  univList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Acıbadem Üniversitesi", mailExt: "live.acibadem.edu.tr" },
    { key: 2, choice: "Bahçeşehir Üniversitesi", mailExt: "bahcesehir.edu.tr" },
    { key: 3, choice: "Bilgi Üniversitesi", mailExt: "bilgiedu.net" },
    { key: 4, choice: "Boğaziçi Üniversitesi", mailExt: "boun.edu.tr" },
    { key: 5, choice: "Galatasaray Üniversitesi", mailExt: "ogr.gsu.edu.tr" },
    { key: 6, choice: "İstanbul Teknik Üniversitesi", mailExt: "itu.edu.tr" },
    { key: 7, choice: "Koç Üniversitesi", mailExt: "ku.edu.tr" },
    { key: 8, choice: "Marmara Üniversitesi", mailExt: "marun.edu.tr" },
    { key: 9, choice: "Mef Üniversitesi", mailExt: "mef.edu.tr" },
    { key: 10, choice: "Mimar Sinan Üniversitesi", mailExt: "ogr.msgsu.edu.tr" },
    { key: 11, choice: "Özyeğin Üniversitesi", mailExt: "ozu.edu.tr" },
    { key: 12, choice: "Sabancı Üniversitesi", mailExt: "sabanciuniv.edu" },
    { key: 13, choice: "Yeditepe Üniversitesi", mailExt: "std.yeditepe.edu.tr" },
    { key: 14, choice: "Yıldız Teknik Üniversitesi", mailExt: "std.yildiz.edu.tr" },
  ],

  religionList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Müslüman" },
    { key: 1, choice: "Hristiyan" },
    { key: 1, choice: "Yahudi" },
    { key: 1, choice: "Deist" },
    { key: 1, choice: "Ateist" },
    { key: 1, choice: "Belirtmek İstemiyorum" },
  ],

  signList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Akrep" },
    { key: 2, choice: "Aslan" },
    { key: 3, choice: "Balık" },
    { key: 4, choice: "Başak" },
    { key: 5, choice: "Boğa" },
    { key: 6, choice: "İkizler" },
    { key: 7, choice: "Koç" },
    { key: 8, choice: "Kova" },
    { key: 9, choice: "Oğlak" },
    { key: 10, choice: "Terazi" },
    { key: 11, choice: "Yay" },
    { key: 12, choice: "Yengeç" },
  ],
  dietList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Her şeyi yerim" },
    { key: 2, choice: "Vejetaryen" },
    { key: 3, choice: "Vegan" },
    { key: 4, choice: "Pesketaryen" },
    { key: 5, choice: "Glutensiz" },
    { key: 6, choice: "Belirtmek İstemiyorum" },
  ],
  smokeAndDrinkList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Sık sık" },
    { key: 2, choice: "Sosyal ortamlarda" },
    { key: 3, choice: "Arada sırada" },
    { key: 4, choice: "Asla" },
    { key: 5, choice: "Belirtmek İstemiyorum" },
  ],
};
