/* 
This file contains list templates and admin defined values

IMPROVEMENTS: 
1) Admim defined values should be retreived from database where they can be changed from admin panel
2)
*/


export var demoAccounts = "(1118, 1206, 141, 32, 33, 35,36, 1454, 1715)";
export var expectationList = {
  takilmak: new Set(),
  kisaSureli: new Set(),
  uzunSureli: new Set(),
  yeniArkadas: new Set(),
  etkinlikBuddy: new Set(),
  bilmiyorum: new Set(),
};
export var genderPreference = {
  women: new Set(),
  men: new Set(),
  non_binary: new Set(),
  hetero: new Set(),
  homo: new Set(),
  bisexual: new Set(),
  pansexual: new Set(),
  asexual: new Set(),
};

export var dailyStats = {
  newUser: 0,
  frozenUser: 0,
  deletedUser: 0,
  dailyRetention: 0,
  dailyUnmatch: 0,
  dailyMatch: 0,
  dailyMatchonEvent: 0,
  totalSwipe: 0,
  dailySwipe: 0,
  dailyLike: 0,
  dailyDislike: 0,
  dailyEventLike: 0,
  newEvents: 0,
  dailyNewReport: 0,
  dailyNewMessages: 0,
  totalMessages: 0,
};

export var cacheStats = {
  cacheSize: 0,
  frozenUser: 0,
  dailyUnmatch: 0,
  newEvents: 0,
  dailyEventLike: 0,
  dailyEventClick: 0,
  dailyDetailClick: 0,
  dailyLinkClick: 0,
  dailyNewReport: 0,
};

export var checkList = {
  0: "live.acibadem.edu.tr",
  1: "bahcesehir.edu.tr",
  2: "bilgiedu.net",
  3: "boun.edu.tr",
  4: "ogr.gsu.edu.tr",
  5: "itu.edu.tr",
  6: "ku.edu.tr",
  7: "marun.edu.tr",
  8: "mef.edu.tr",
  9: "ogr.msgsu.edu.tr",
  10: "ozu.edu.tr",
  11: "sabanciuniv.edu",
  12: "std.yeditepe.edu.tr",
  13: "std.yildiz.edu.tr",
  14: "ogrenci.ankara.edu.tr",
  15: "mail.baskent.edu.tr",
  16: "ug.bilkent.edu.tr",
  17: "hacettepe.edu.tr",
  18: "etu.edu.tr",
  19: "metu.edu.tr",
  20: "isik.edu.tr",
  21: "stu.okan.edu.tr",
  22: "st.biruni.edu.tr",
  23: "stu.fbu.edu.tr",
  24: "stu.gedik.edu.tr",
  25: "ogr.halic.edu.tr",
  26: "stu.aydin.edu.tr",
  27: "ogr.gelisim.edu.tr",
  28: "stu.iku.edu.tr",
  29: "medeniyet.edu.tr",
  30: "std.medipol.edu.tr",
  31: "istanbulticaret.edu.tr",
  32: "ogr.iuc.edu.tr",
  33: "stu.istinye.edu.tr",
  34: "stu.khas.edu.tr",
  35: "st.maltepe.edu.tr",
  36: "ogrenci.sbu.edu.tr",
  37: "stud.tau.edu.tr",
  38: "tedu.edu.tr",
  39: "std.ankaramedipol.edu.tr",
  40: "ybu.edu.tr",
  41: "student.atilim.edu.tr",
  42: "ufuk.edu.tr",
  43: "gazi.edu.tr",
  44: "ogrenci.ege.edu.tr",
  45: "ieu.edu.tr",
  46: "ogr.deu.edu.tr",
  47: "ogr.ikc.edu.tr",
  48: "stu.yasar.edu.tr",
  49: "std.nisantasi.edu.tr",
  50: "student.cankaya.edu.tr",
  51: "ogrenci.beykoz.edu.tr",
};

//Inner lists in appList are merged in order to be sent front end easily
export var appLists = {
  genderList: [
    { key: 0, choice: "Kadın" },
    { key: 1, choice: "Erkek" },
    { key: 2, choice: "Non-Binary" },
    { key: 3, choice: "Belirtmek İstemiyorum" },
  ],
  univList: {
    ankara: [
      { key: 50, choice: "Ankara Çankaya Üniversitesi", mailExt: "student.cankaya.edu.tr" },
      { key: 39, choice: "Ankara Medipol Üniversitesi", mailExt: "std.ankaramedipol.edu.tr" },
      { key: 41, choice: "Atılım Üniversitesi", mailExt: "student.atilim.edu.tr" },
      { key: 14, choice: "Ankara Üniversitesi", mailExt: "ogrenci.ankara.edu.tr" },
      { key: 15, choice: "Başkent Üniversitesi", mailExt: "mail.baskent.edu.tr" },
      { key: 16, choice: "Bilkent Üniversitesi", mailExt: "ug.bilkent.edu.tr" },
      { key: 43, choice: "Gazi Üniversitesi", mailExt: "gazi.edu.tr" },
      { key: 17, choice: "Hacettepe Üniversitesi", mailExt: "hacettepe.edu.tr" },
      { key: 38, choice: "TED Üniversitesi", mailExt: "tedu.edu.tr" },
      { key: 18, choice: "TOBB", mailExt: "etu.edu.tr" },
      { key: 19, choice: "ODTÜ", mailExt: "metu.edu.tr" },
      { key: 42, choice: "Ufuk Üniversitesi", mailExt: "ufuk.edu.tr" },
      { key: 40, choice: "Yıldırım Beyazıt Üniversitesi", mailExt: "aybu.edu.tr" },
    ],
    istanbul: [
      { key: 0, choice: "Acıbadem Üniversitesi", mailExt: "live.acibadem.edu.tr" },
      { key: 1, choice: "Bahçeşehir Üniversitesi", mailExt: "bahcesehir.edu.tr" },
      { key: 51, choice: "Beykoz Üniversitesi", mailExt: "ogrenci.beykoz.edu.tr" },
      { key: 2, choice: "Bilgi Üniversitesi", mailExt: "bilgiedu.net" },
      { key: 22, choice: "Biruni Ünivresitesi", mailExt: "st.biruni.edu.tr" },
      { key: 3, choice: "Boğaziçi Üniversitesi", mailExt: "boun.edu.tr" },
      { key: 23, choice: "Fenerbahçe Üniversitesi", mailExt: "stu.fbu.edu.tr" },
      { key: 4, choice: "Galatasaray Üniversitesi", mailExt: "ogr.gsu.edu.tr" },
      { key: 24, choice: "Gedik Üniversitesi", mailExt: "stu.gedik.edu.tr" },
      { key: 25, choice: "Haliç Üniversitesi", mailExt: "ogr.halic.edu.tr" },
      { key: 20, choice: "Işık Üniversitesi", mailExt: "isik.edu.tr" },
      { key: 26, choice: "İstanbul Aydın Üniversitesi", mailExt: "stu.aydin.edu.tr" },
      { key: 5, choice: "İstanbul Teknik Üniversitesi", mailExt: "itu.edu.tr" },
      { key: 27, choice: "İstanbul Gelişim Üniversitesi", mailExt: "ogr.gelisim.edu.tr" },
      { key: 28, choice: "İstanbul Kültür Üniversitesi", mailExt: "stu.iku.edu.tr" },
      { key: 29, choice: "İstanbul Medeniyet Üniversitesi", mailExt: "medeniyet.edu.tr" },
      { key: 30, choice: "İstanbul Medipol Üniversitesi", mailExt: "std.medipol.edu.tr" },
      { key: 31, choice: "İstanbul Ticaret Üniversitesi", mailExt: "istanbulticaret.edu.tr" },
      { key: 32, choice: "İstanbul Üniversitesi-Cerrahpaşa", mailExt: "ogr.iuc.edu.tr" },
      { key: 33, choice: "İstinye Üniversitesi", mailExt: "stu.istinye.edu.tr" },
      { key: 34, choice: "Kadir Has Üniversitesi", mailExt: "stu.khas.edu.tr" },
      { key: 6, choice: "Koç Üniversitesi", mailExt: "ku.edu.tr" },
      { key: 35, choice: "Maltepe Üniversitesi", mailExt: "st.maltepe.edu.tr" },
      { key: 7, choice: "Marmara Üniversitesi", mailExt: "marun.edu.tr" },
      { key: 8, choice: "Mef Üniversitesi", mailExt: "mef.edu.tr" },
      { key: 9, choice: "Mimar Sinan Üniversitesi", mailExt: "ogr.msgsu.edu.tr" },
      { key: 49, choice: "Nişantaşı Üniversitesi", mailExt: "std.nisantasi.edu.tr" },
      { key: 21, choice: "Okan Üniversitesi", mailExt: "stu.okan.edu.tr" },
      { key: 10, choice: "Özyeğin Üniversitesi", mailExt: "ozu.edu.tr" },
      { key: 11, choice: "Sabancı Üniversitesi", mailExt: "sabanciuniv.edu" },
      { key: 36, choice: "Sağlık Bilimleri Üniversitesi", mailExt: "ogrenci.sbu.edu.tr" },
      { key: 37, choice: "Türk Alman üniversitesi", mailExt: "stud.tau.edu.tr" },
      { key: 12, choice: "Yeditepe Üniversitesi", mailExt: "std.yeditepe.edu.tr" },
      { key: 13, choice: "Yıldız Teknik Üniversitesi", mailExt: "std.yildiz.edu.tr" },
    ],
    izmir: [
      { key: 44, choice: "Ege Üniversitesi", mailExt: "ogrenci.ege.edu.tr" },
      { key: 46, choice: "İzmir Dokuz Eylül Üniversitesi", mailExt: "ogr.deu.edu.tr" },
      { key: 45, choice: "İzmir Ekonomi Üniversitesi", mailExt: "ieu.edu.tr" },
      { key: 47, choice: "Katip Çelebi Üniversitesi", mailExt: "ogr.ikc.edu.tr" },
      { key: 48, choice: "Yaşar Üniversitesi", mailExt: "stu.yasar.edu.tr" },
    ],
  },

  religionList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Müslüman" },
    { key: 1, choice: "Hristiyan" },
    { key: 1, choice: "Yahudi" },
    { key: 1, choice: "Deist" },
    { key: 1, choice: "Ateist" },
    { key: 1, choice: "Belirtmek İstemiyorum" },
  ],
  signList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Akrep" },
    { key: 2, choice: "Aslan" },
    { key: 3, choice: "Balık" },
    { key: 4, choice: "Başak" },
    { key: 5, choice: "Boğa" },
    { key: 6, choice: "İkizler" },
    { key: 7, choice: "Koç" },
    { key: 8, choice: "Kova" },
    { key: 9, choice: "Oğlak" },
    { key: 10, choice: "Terazi" },
    { key: 11, choice: "Yay" },
    { key: 12, choice: "Yengeç" },
  ],
  dietList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Her şeyi yerim" },
    { key: 2, choice: "Vejeteryan" },
    { key: 3, choice: "Vegan" },
    { key: 4, choice: "Pesketaryen" },
    { key: 5, choice: "Glutensiz" },
    { key: 6, choice: "Belirtmek İstemiyorum" },
  ],
  smokeAndDrinkList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Sık sık" },
    { key: 2, choice: "Sosyal ortamlarda" },
    { key: 3, choice: "Arada sırada" },
    { key: 4, choice: "Asla" },
    { key: 5, choice: "Belirtmek İstemiyorum" },
  ],
  interestedSexList: [
    { key: 0, choice: "Kadın" },
    { key: 1, choice: "Erkek" },
    { key: 2, choice: "Herkes" },
  ],
  sexualOrientationList: [
    { key: 0, choice: "Kadın" },
    { key: 1, choice: "Erkek" },
    { key: 2, choice: "Herkes" },
  ],
  expectationList: [
    { key: 0, choice: "" },
    { key: 1, choice: "Takılmak" },
    { key: 2, choice: "Kısa Süreli İlişki" },
    { key: 3, choice: "Uzun Süreli İlişki" },
    { key: 4, choice: "Yeni Arkadaşlıklar" },
    { key: 5, choice: "Etkinliklere Eşlik Edecek Biri" },
    { key: 6, choice: "Ne istediğimi Bilmiyorum" },
  ],
  cityList: [
    { idx: 1, key: "ankara", choice: "Ankara" },
    { idx: 2, key: "istanbul", choice: "İstanbul" },
    { idx: 3, key: "izmir", choice: "İzmir" },
  ],
};
